---
- name: Converge
  hosts: all
  become: false

  pre_tasks:
    - name: Wait for systemd to complete initialization
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_facts['service_mgr'] == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

    - name: Print ansible_facts
      ansible.builtin.debug:
        var: ansible_facts
        verbosity: 2

  roles:
    - role: wesmarcum.openssh
