---
- name: Prepare
  hosts: all
  gather_facts: false
  become: false

  tasks:
    - name: Init pacman key
      ansible.builtin.raw: /usr/bin/pacman-key --init
      changed_when: false

    - name: Check for python
      ansible.builtin.raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

    - name: Install python
      ansible.builtin.raw: pacman -Syu --noconfirm python
      when: check_python.rc != 0

    - name: Install sudo
      ansible.builtin.package:
        name: sudo
        state: present
