---
- name: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
  become: true

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true
