---
# Owner/group for config files
openssh_owner: "root"
openssh_group: "root"

# SSH packages to install
openssh_packages:
  - openssh-server
  - openssh-sftp-server

# Name of the OpenSSH service
openssh_service: "ssh"

# Command to use to validate the sshd configuration
openssh_validate_cmd: "/usr/sbin/sshd -t -f %s"
