---
- name: Converge
  hosts: all
  become: false

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Wait for systemd to complete initialization
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: ansible_facts['service_mgr'] == 'systemd'
      changed_when: false
      failed_when: systemctl_status.rc > 1

    - name: Create ssh runtime dirs (Debian/Ubuntu bug 45234)
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
        owner: root
        group: root
      become: true
      when: ansible_facts['os_family'] == 'Debian'
      loop:
        - /var/run/sshd
        - /run/sshd

    - name: Print ansible_facts
      ansible.builtin.debug:
        var: ansible_facts
        verbosity: 2

  roles:
    - role: wesmarcum.openssh
